/**
 * Which way a train actually leaves, without asking about it.
 *
 * A line-up carries an origin, a destination and a time. It does not carry the route,
 * and the route is the thing "which direction" actually means. From Upminster the 00:33
 * and the 00:57 are both to Shoeburyness: one runs down the Ockendon branch through
 * Grays, Tilbury and Stanford-le-Hope, the other takes the main line through Basildon.
 * Classifying by the bearing to the destination puts both in the same bucket, and the
 * board's answer to "last train south" came out as 18:34 when the last train that
 * reaches Grays is 00:33.
 *
 * The route is only visible in each service's calling pattern, which costs a request per
 * train. So `scripts/generate-adjacency.mjs` walks those patterns **offline** and reduces
 * them to one fact per station per compass sector: a **waypoint** that every service
 * leaving that way calls at, and no service leaving another way calls at. At runtime
 * `filterTo=<waypoint>` then partitions the line-up exactly, for the same single request
 * the unfiltered query used to cost.
 *
 * `null` is a real and frequent answer. Upminster westbound has no waypoint, because the
 * Fenchurch Street main line and the Romford branch share no station — there is nothing
 * that selects one without selecting the other. A sector sampled fewer than three times
 * gets none either, since a waypoint that a fast service skips would silently drop trains,
 * which is worse than the known wrongness it replaces. Callers fall back to destination
 * bearing in both cases.
 *
 * Generated by `npm run national:adjacency`, resumable across days. Server-side only,
 * for the same reason as `nationalStations`: the app receives boards, not tables.
 */

import 'server-only';
import adjacencyData from '../data/adjacency.json';
import { COMPASS_POINTS, type Compass } from './compass.ts';

export interface SectorRoute {
  /**
   * A station that pins this direction, or null when none exists.
   *
   * Every service leaving this way calls here; nothing leaving another way does.
   */
  waypoint: string | null;
  /** The stations services call at first when leaving this way. */
  firstCalls: string[];
  /** Where this way goes, most frequent first, for the direction control's label. */
  destinations: string[];
  /** How many sampled routes this is based on. Below three, `waypoint` is null. */
  samples: number;
}

export type StationRoutes = Partial<Record<Compass, SectorRoute>>;

interface AdjacencyFile {
  generatedAt: string;
  referenceDate: string;
  stations: Record<string, StationRoutes>;
}

const data = adjacencyData as AdjacencyFile;

export const adjacencyGeneratedAt = data.generatedAt;

/** Everything known about the routes out of a station, or undefined if unwalked. */
export function routesFrom(crs: string): StationRoutes | undefined {
  return data.stations[crs.toUpperCase()];
}

/**
 * The waypoint that selects one direction out of a station.
 *
 * Undefined means "no usable waypoint" and is the signal to fall back, whether because
 * the walk has not reached this station yet, because the sector was too thinly sampled,
 * or because no such station exists.
 */
export function waypointFor(crs: string, direction: Compass): string | undefined {
  return routesFrom(crs)?.[direction]?.waypoint ?? undefined;
}

/**
 * Which directions have track, as a fact about the network rather than a count of
 * today's destinations.
 *
 * Strictly better than counting: a direction with trains that all happen to terminate
 * beyond a curve used to read as empty, and a direction whose only services are
 * seasonal used to vanish on the days they do not run. Undefined when the station has
 * not been walked, so the caller keeps counting.
 */
export function directionsWithTrack(crs: string): Compass[] | undefined {
  const routes = routesFrom(crs);
  if (!routes) return undefined;
  return COMPASS_POINTS.filter((point) => routes[point]);
}
