/**
 * Every station in Great Britain, server-side only.
 *
 * `data/national.json` is 2,619 stations and about 360KB. It is imported here rather
 * than in anything the browser can reach, and guarded with `server-only` for the same
 * reason `lib/geo.ts` is: a few thousand coordinates are a pointless download on a
 * platform with one bar of signal, and the native app carries its own copy anyway.
 *
 * Generated by `npm run national:data`. Nothing in this file is hand-maintained, and
 * no CRS code in this project has ever been typed by hand.
 */

import 'server-only';
import nationalData from '../data/national.json';
import type { GeoPoint } from './nearest.ts';

export interface NationalStation extends GeoPoint {
  crs: string;
  name: string;
  /** NaPTAN locality, for telling two Newports apart. Frequently null. */
  locality: string | null;
  town: string | null;
}

interface NationalFile {
  generatedAt: string;
  stationCount: number;
  unplaced: { crs: string; name: string; reason: string }[];
  stations: NationalStation[];
}

const data = nationalData as NationalFile;

export const nationalStations: readonly NationalStation[] = data.stations;

/**
 * Stops the API can query but that have no published position.
 *
 * Two rail-air interchanges that are not rail stations, and Winslow, which reopened
 * on East West Rail before NaPTAN published it. Exposed rather than hidden: a service
 * bound for one of these cannot be given a direction, and that should be traceable
 * rather than mysterious.
 */
export const unplacedStops: readonly { crs: string; name: string; reason: string }[] =
  data.unplaced ?? [];

const canonical = (value: string): string => value.toLowerCase().replace(/[^a-z0-9]/g, '');

const byCrs = new Map<string, NationalStation>();
const byName = new Map<string, NationalStation>();

for (const station of data.stations) {
  byCrs.set(station.crs.toUpperCase(), station);
  const key = canonical(station.name);
  // First wins. Names are unique in the generated list -- the generator asserts CRS
  // uniqueness and no two stations within 25m -- but a future duplicate should not
  // silently replace an earlier entry.
  if (!byName.has(key)) byName.set(key, station);
}

export const findStationByCrs = (crs: string): NationalStation | undefined =>
  byCrs.get(crs.trim().toUpperCase());

/**
 * Resolve a station from the description a line-up gives for it.
 *
 * Destination pairs carry a description and usually **no** `shortCodes` — verified
 * against the live API, and the reason the web app matches destinations by name. So
 * name is the primary key here, not a fallback.
 */
export const findStationByName = (name: string): NationalStation | undefined =>
  byName.get(canonical(name));

/** The position of a destination, by whichever of its identifiers resolves. */
export function coordinateFor(
  names: readonly string[],
  codes: readonly string[] = []
): GeoPoint | null {
  for (const name of names) {
    const station = findStationByName(name);
    if (station) return { lat: station.lat, lon: station.lon };
  }
  for (const code of codes) {
    const station = findStationByCrs(code);
    if (station) return { lat: station.lat, lon: station.lon };
  }
  return null;
}
