import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import { buildSpatialIndex, distanceKm, nearestByScan, type GeoPoint } from './nearest.ts';

/**
 * The national list is read rather than imported, so these tests need no bundler and
 * no JSON import assertion. It is generated by `npm run national:data`.
 */
interface NationalStation extends GeoPoint {
  crs: string;
  name: string;
}

const national: NationalStation[] = JSON.parse(
  readFileSync(new URL('../data/national.json', import.meta.url), 'utf8')
).stations;

const index = buildSpatialIndex(national);

const crsAt = (position: GeoPoint, limit = 4) =>
  index.nearest(position, limit).map((n) => n.station.crs);

// ------------------------------------------------------------------- the data

test('the national list is present and plausible', () => {
  assert.ok(national.length > 2500, `expected the whole network, got ${national.length}`);
  assert.equal(index.size, national.length);
  // If every station landed in one cell the grid is doing nothing.
  assert.ok(index.cells > 500, `only ${index.cells} occupied cells`);
});

// ------------------------------------------------------------- known answers

test('a position on a platform finds that platform', () => {
  // Upminster, from its own generated coordinates.
  const upminster = national.find((s) => s.crs === 'UPM');
  assert.ok(upminster);
  assert.equal(crsAt(upminster, 1)[0], 'UPM');
});

test('the far ends of the country resolve to themselves', () => {
  for (const crs of ['PNZ', 'INV', 'WIC', 'THO', 'PMH']) {
    const station = national.find((s) => s.crs === crs);
    if (!station) continue; // the list is generated; do not assert a code exists
    assert.equal(crsAt(station, 1)[0], crs, `${crs} did not find itself`);
  }
});

test('a position between stations ranks them by real distance', () => {
  // Roughly the Thames between Grays and Tilbury.
  const results = index.nearest({ lat: 51.47, lon: 0.35 }, 4);
  assert.equal(results.length, 4);
  for (let i = 1; i < results.length; i++) {
    assert.ok(
      results[i].distanceKm >= results[i - 1].distanceKm,
      'results came back out of order'
    );
  }
});

// -------------------------------------------------- agreement with brute force

/**
 * The test that matters.
 *
 * A grid that returns *an* answer quickly is worthless; it has to return *the* answer.
 * The failure mode this catches is the obvious implementation -- search the 3×3 block
 * and stop -- which is wrong exactly when the nearest station sits just across a cell
 * boundary, and which looks perfectly fine in casual use.
 */
function assertAgreesEverywhere(positions: GeoPoint[], limit: number): void {
  for (const position of positions) {
    const fromIndex = index.nearest(position, limit);
    const fromScan = nearestByScan(national, position, limit);

    assert.equal(fromIndex.length, fromScan.length, `length differs at ${position.lat},${position.lon}`);
    for (let i = 0; i < fromScan.length; i++) {
      // Compare distances rather than identity: several stations share a position to
      // within millimetres, and either is a correct answer at that rank.
      assert.ok(
        Math.abs(fromIndex[i].distanceKm - fromScan[i].distanceKm) < 1e-9,
        `rank ${i} differs at ${position.lat},${position.lon}: ` +
          `${fromIndex[i].station.crs} ${fromIndex[i].distanceKm.toFixed(6)}km vs ` +
          `${fromScan[i].station.crs} ${fromScan[i].distanceKm.toFixed(6)}km`
      );
    }
  }
}

/** Deterministic pseudo-random, so a failure is reproducible. */
function* lcg(seed: number): Generator<number> {
  let state = seed >>> 0;
  for (;;) {
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    yield state / 0x1_0000_0000;
  }
}

test('the grid agrees with a full scan across Great Britain', () => {
  const random = lcg(20260801);
  const positions: GeoPoint[] = [];
  for (let i = 0; i < 1500; i++) {
    positions.push({
      lat: 49.9 + random.next().value! * (58.7 - 49.9),
      lon: -7.6 + random.next().value! * (1.8 + 7.6),
    });
  }
  assertAgreesEverywhere(positions, 4);
});

test('the grid agrees right next to every station, where boundaries bite', () => {
  // Offsets of a few hundred metres, which is where a station's own cell and the
  // answer's cell most often differ.
  const random = lcg(981);
  const positions: GeoPoint[] = [];
  for (const station of national) {
    positions.push({
      lat: station.lat + (random.next().value! - 0.5) * 0.02,
      lon: station.lon + (random.next().value! - 0.5) * 0.02,
    });
  }
  assertAgreesEverywhere(positions, 3);
});

test('the grid agrees at the extremes of latitude', () => {
  // A degree of longitude is 71km at Penzance and 57km at Wick. Anything that assumes
  // a cell is a fixed number of kilometres across is wrong at one end or the other.
  const random = lcg(4242);
  const positions: GeoPoint[] = [];
  for (const centre of [
    { lat: 58.44, lon: -3.09 }, // Wick
    { lat: 50.12, lon: -5.53 }, // Penzance
    { lat: 60.15, lon: -1.15 }, // Shetland, well past any station
  ]) {
    for (let i = 0; i < 200; i++) {
      positions.push({
        lat: centre.lat + (random.next().value! - 0.5) * 1.5,
        lon: centre.lon + (random.next().value! - 0.5) * 3,
      });
    }
  }
  assertAgreesEverywhere(positions, 4);
});

// ---------------------------------------------------------------- edge cases

test('a position far offshore still returns the nearest stations', () => {
  // Mid-North Sea. Every ring around the query cell is empty for a long way.
  const results = index.nearest({ lat: 56.0, lon: 3.0 }, 3);
  assert.equal(results.length, 3);
  assert.deepEqual(
    results.map((r) => r.station.crs),
    nearestByScan(national, { lat: 56.0, lon: 3.0 }, 3).map((r) => r.station.crs)
  );
});

test('asking for more stations than exist returns all of them', () => {
  const tiny = buildSpatialIndex([
    { crs: 'AAA', lat: 51.5, lon: -0.1 },
    { crs: 'BBB', lat: 55.0, lon: -3.0 },
  ]);
  assert.equal(tiny.nearest({ lat: 51.5, lon: -0.1 }, 10).length, 2);
});

test('an empty index answers with nothing rather than failing', () => {
  const empty = buildSpatialIndex<GeoPoint>([]);
  assert.deepEqual(empty.nearest({ lat: 51.5, lon: -0.1 }), []);
  assert.equal(empty.size, 0);
});

test('a nonsense position answers with nothing rather than failing', () => {
  assert.deepEqual(index.nearest({ lat: Number.NaN, lon: 0 }), []);
  assert.deepEqual(index.nearest({ lat: 51.5, lon: -0.1 }, 0), []);
});

test('stations without usable coordinates are left out of the index', () => {
  const withJunk = buildSpatialIndex([
    { crs: 'AAA', lat: 51.5, lon: -0.1 },
    { crs: 'BAD', lat: Number.NaN, lon: 0 },
  ] as (GeoPoint & { crs: string })[]);
  assert.equal(withJunk.size, 1);
});

// ----------------------------------------------------------------- geometry

test('distance is symmetric and zero for a point against itself', () => {
  const a = { lat: 51.559018, lon: 0.25088 };
  const b = { lat: 50.121, lon: -5.533 };
  assert.equal(distanceKm(a, a), 0);
  assert.ok(Math.abs(distanceKm(a, b) - distanceKm(b, a)) < 1e-9);
});

test('a known distance comes out right', () => {
  // Upminster to Penzance. 159km south and 407km west, so 436km great-circle --
  // checked against a flat-earth approximation, which at this range agrees to a
  // couple of hundred metres.
  const km = distanceKm({ lat: 51.559018, lon: 0.25088 }, { lat: 50.1217, lon: -5.5326 });
  assert.ok(km > 435 && km < 438, `got ${km.toFixed(1)}km`);
});

test('a cell size that puts everything in one bucket still gives right answers', () => {
  // Degenerate on purpose: with 90° cells the grid stops helping, and the results
  // must not change. If they do, the answer depended on the bucketing.
  const coarse = buildSpatialIndex(national, 90);
  const position = { lat: 53.4, lon: -2.1 };
  assert.deepEqual(
    coarse.nearest(position, 4).map((r) => r.station.crs),
    nearestByScan(national, position, 4).map((r) => r.station.crs)
  );
});
