/**
 * The bundled station list.
 *
 * No API call is needed to pick a station. `data/stations.json` is generated by
 * `scripts/generate-stations.mjs`, which harvests real calling patterns from the
 * API and joins them to NaPTAN for coordinates. Every CRS code in it came from
 * the API; none were typed by hand, which is the single likeliest bug in a build
 * like this.
 */

import stationData from '../data/stations.json';

export interface Station {
  /** Three-letter CRS code, as returned by the API. */
  crs: string;
  name: string;
  /** TIPLOC, kept because it is the join key to external datasets. */
  tiploc: string;
  lat: number;
  lon: number;
  /** TOC codes observed calling here, e.g. `["CC"]` or `["LE","XR"]`. */
  operators: string[];
  /**
   * Directions in which the corridor actually continues from here, derived from real
   * calling patterns at generation time.
   *
   * Shenfield is `["west"]` and Shoeburyness `["west"]`, because both sit at the end
   * of what this app covers. Eastbound from either, the honest answer is nothing --
   * and knowing that in advance means answering without calling the API at all.
   */
  onward?: ('east' | 'west')[];
}

export interface RouteMarkerEntry {
  crs: string;
  label: string;
  station: string;
}

interface StationData {
  generatedAt: string;
  apiVersion: string;
  routeMarkers: RouteMarkerEntry[];
  stations: Station[];
}

const data = stationData as StationData;

export const stations: Station[] = data.stations;
export const routeMarkers: RouteMarkerEntry[] = data.routeMarkers;
export const stationDataGeneratedAt: string = data.generatedAt;

const byCrs = new Map<string, Station>(data.stations.map((s) => [s.crs, s]));

export const findStation = (crs: string): Station | undefined =>
  byCrs.get(crs.trim().toUpperCase());

export const isKnownStation = (crs: string): boolean => byCrs.has(crs.trim().toUpperCase());

const canonicalName = (value: string): string =>
  value.toLowerCase().replace(/[^a-z0-9]/g, '');

const byCanonicalName = new Map<string, Station>(
  data.stations.map((station) => [canonicalName(station.name), station])
);

/**
 * Look a station up by its display name.
 *
 * Needed because a service's origin and destination come back as a description with
 * no codes attached -- `{ description: "Shoeburyness" }`, no `shortCodes`. Matching
 * on the name is therefore the only way to tell "bound for somewhere in scope" from
 * "bound for Norwich" without spending a request on the calling pattern. Both sides
 * of the comparison come from the same API, so the names agree exactly.
 */
export const findStationByName = (name: string): Station | undefined =>
  byCanonicalName.get(canonicalName(name));

export const isKnownStationName = (name: string): boolean =>
  byCanonicalName.has(canonicalName(name));


// ------------------------------------------------------------------- searching

const normalise = (value: string): string =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9 ]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

/** Cached so filter-as-you-type does not re-normalise the whole list per keystroke. */
const searchIndex: { station: Station; haystack: string; words: string[] }[] = data.stations.map(
  (station) => {
    const haystack = normalise(station.name);
    return { station, haystack, words: haystack.split(' ') };
  }
);

/**
 * Filter-as-you-type over the bundled list.
 *
 * Ranked so the obvious answer lands first: exact CRS, then names starting with
 * the query, then a word starting with it, then anything containing it. Typing
 * "sou" should not bury Southend Central under Sudbury.
 */
export function searchStations(query: string, limit = 8): Station[] {
  const raw = query.trim();
  if (!raw) return [];

  const upper = raw.toUpperCase();
  const needle = normalise(raw);
  if (!needle) return [];

  const scored: { station: Station; score: number }[] = [];

  for (const entry of searchIndex) {
    let score = -1;

    if (entry.station.crs === upper) score = 0;
    else if (entry.haystack.startsWith(needle)) score = 1;
    else if (entry.words.some((word) => word.startsWith(needle))) score = 2;
    else if (entry.haystack.includes(needle)) score = 3;
    // "London" is a prefix on many names, so also allow matching past it.
    else if (entry.haystack.replace(/^london /, '').startsWith(needle)) score = 2;

    if (score >= 0) scored.push({ station: entry.station, score });
  }

  scored.sort(
    (a, b) => a.score - b.score || a.station.name.localeCompare(b.station.name)
  );
  return scored.slice(0, limit).map((entry) => entry.station);
}

// -------------------------------------------------------------------- geography

// One haversine in the project, not two. `lib/nearest.ts` owns it because that is
// where it is tested; this module re-exports it so the existing callers are unchanged.
// Imported as well as re-exported, since `nearestStations` below calls it.
import { distanceKm } from './nearest.ts';
export { distanceKm };

export interface NearbyStation {
  station: Station;
  distanceKm: number;
}

/**
 * Nearest stations to a position.
 *
 * The highest-value feature in the app: the typical use is standing on a
 * platform, wanting the "from" field filled in one tap. Returns a short list
 * rather than one result, because at Stratford or Barking the nearest station by
 * straight-line distance is not always the one you are stood on.
 */
/**
 * How far away a station can be and still answer "where am I?".
 *
 * There is always a nearest station, which is the problem. Without a bound, standing
 * in San Francisco fills the field with **Thurso** — 7,907km away, and genuinely the
 * closest British station to California. The index is right and the answer is absurd.
 *
 * **It is not a test of which country you are in, and does not try to be.** Cape Wrath
 * is 70.7km from the nearest railhead and Kinlochbervie 63.3km, while Belfast is 67.7km
 * from Stranraer and Douglas 68.2km from Nethertown: remote Great Britain is *further
 * from a station* than Northern Ireland or the Isle of Man are. No threshold separates
 * them, so this rules out the absurd and nothing more.
 *
 * Mirrors `Stations.plausibleRadiusMetres` in `LastTrainCore`. The two must agree.
 */
export const PLAUSIBLE_RADIUS_KM = 100;

export function nearestStations(
  position: { lat: number; lon: number },
  limit = 4,
  withinKm = PLAUSIBLE_RADIUS_KM
): NearbyStation[] {
  return data.stations
    .map((station) => ({ station, distanceKm: distanceKm(position, station) }))
    .sort((a, b) => a.distanceKm - b.distanceKm)
    .filter((candidate) => candidate.distanceKm <= withinKm)
    .slice(0, limit);
}
