import Foundation

import LastTrainCore

// MARK: - The national station list

/**
 One copy of the station data, read from where the generator wrote it.

 `data/national.json` is generated by `npm run national:data` and lives at the repo
 root. The Swift package reads it from there rather than keeping a second copy: it is
 generated data, and two copies of generated data drift the moment someone regenerates
 one of them.

 That does mean the tests know where they sit in the repo, which is a fair trade for a
 test and is exactly what `lib/nearest.test.ts` does on the JavaScript side.

 **When the app target exists this decision needs revisiting**, because IOS.md §5 has
 the app bundling stations — at that point the generator should write the copy into
 the app's resources, so the single source of truth stays the generator rather than
 becoming a file somebody remembers to sync.
 */
struct NationalStation: Decodable, Located, Sendable, Equatable {
    let crs: String
    let name: String
    let lat: Double
    let lon: Double

    var coordinate: Coordinate { Coordinate(lat: lat, lon: lon) }
}

private struct NationalFile: Decodable {
    let stations: [NationalStation]
}

enum National {
    /// `ios/Tests/LastTrainCoreTests/Fixtures.swift` → repo root → `data/national.json`.
    static let url: URL = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()   // LastTrainCoreTests
        .deletingLastPathComponent()   // Tests
        .deletingLastPathComponent()   // ios
        .deletingLastPathComponent()   // repo root
        .appendingPathComponent("data/national.json")

    static let stations: [NationalStation] = {
        guard let data = try? Data(contentsOf: url) else {
            preconditionFailure(
                "data/national.json not found at \(url.path). Run `npm run national:data`."
            )
        }
        guard let decoded = try? JSONDecoder().decode(NationalFile.self, from: data) else {
            preconditionFailure("data/national.json could not be decoded")
        }
        return decoded.stations
    }()

    static func find(_ crs: String) -> NationalStation? {
        stations.first { $0.crs == crs }
    }
}

/// Deterministic pseudo-random, so a failure is reproducible.
struct Lcg {
    private var state: UInt32

    init(seed: UInt32) { self.state = seed }

    mutating func next() -> Double {
        state = state &* 1_664_525 &+ 1_013_904_223
        return Double(state) / Double(UInt32.max)
    }
}

/**
 An absolute instant, written as UTC.

 Test inputs standing for "now" are always written this way, with the London time
 they correspond to in a comment, because those two differing by an hour through BST
 is the entire reason these tests exist.
 */
func utcInstant(_ iso: String) -> Date {
    let formatter = ISO8601DateFormatter()
    formatter.formatOptions = [.withInternetDateTime]
    guard let date = formatter.date(from: iso) else {
        preconditionFailure("bad fixture instant: \(iso)")
    }
    return date
}

/// Renders an instant back to UTC ISO, for asserting what a London string resolved to.
func utcString(_ date: Date?) -> String? {
    guard let date else { return nil }
    let formatter = ISO8601DateFormatter()
    formatter.formatOptions = [.withInternetDateTime]
    formatter.timeZone = TimeZone(identifier: "UTC")
    return formatter.string(from: date)
}
